#6 Add component diagram for books service
e-library-on-containers/e-library-on-containers pull request #29
Opened 2022-12-01 20:07 UTC by bubus128

Closes #6 
![image](https://user-images.githubusercontent.com/72924140/205148051-de08f940-b660-4b11-8ae6-a2be6647aff0.png)

2022-12-02 08:42 UTC, RafKulas requested changes, later dismissed

2022-12-02 08:42 UTC, RafKulas commented on c4builder/src/3 Component Diagrams/4 Books service/books-service.puml
> +Rel(booksService, rabbit, "Uses")
Don't use `Uses` everywhere. For example, `booksWorker` and `booksService` don't just use rabbitmq but rather consumes and publish events.
Your service is almost identical to [mine](https://github.com/e-library-on-containers/e-library-on-containers/blob/develop/c4builder/src/3%20Component%20Diagrams/3%20Rentals%20service/rentals-service.puml), take a look on it, it could help 😝

2022-12-02 08:42 UTC, RafKulas commented on c4builder/src/3 Component Diagrams/4 Books service/books-service.puml
> +}
Please give more details. Just from looking at it I think it's just CRUD app

2022-12-02 08:42 UTC, RafKulas commented on c4builder/src/3 Component Diagrams/4 Books service/books-service.md
> +According to *CQS* (Command-query separation) principles, in the system *Queries* retrieves data from database and processes it before returning it to user (without any side effects on system state)
You can also write something about EventSourcing and write some more details

2023-01-28 09:16 UTC, krzysztofzajaczkowski requested changes
Remove .gitignore changes.

2023-01-28 11:56 UTC, krzysztofzajaczkowski approved these changes

2023-01-28 12:00 UTC, merged